version: "3"
services:
    certbot:
        image: certbot/certbot:latest
        volumes:
        - ./certbot/www:/var/www/certbot
        - ./certbot/conf:/etc/letsencrypt
        command: certonly --webroot -w /var/www/certbot --email bartoszzziemba@gmail.com -d nextbikewrapped.online --agree-tos
    nextbikewrapped-front:
        build:
            context: .
            dockerfile: frontend/Dockerfile
            args:
                - API_URL=${API_URL}
        ports:
            - 80:80
            - 443:443
        restart: always
        volumes:
            - ./frontend:/usr/src/app/frontend
            - ./certbot/www:/var/www/certbot
            - ./certbot/conf:/etc/letsencrypt
            - ./frontend/nginx.conf:/etc/nginx/nginx.conf

        
        environment:
            - API_URL=${API_URL}

    nextbikewrapped-back:
        build:
            context: .
            dockerfile: backend/Dockerfile
        ports:
            - 5000:5000
        volumes:
            - ./backend:/usr/src/app/backend
        environment:
            - GOOGLE_API_KEY=${GOOGLE_API_KEY}
            - GOOGLE_SIGNING_KEY=${GOOGLE_SIGNING_KEY}
            - NEO4J_URI=${NEO4J_URI}
            - NEO4J_USERNAME=${NEO4J_USERNAME}
            - NEO4J_PASSWORD=${NEO4J_PASSWORD}
            - AURA_INSTANCEID=${AURA_INSTANCEID}
            - AURA_INSTANCENAME=${AURA_INSTANCENAME}
            - MONGODB_URI=${MONGODB_URI}
