name: Docker Image CI

on:
  push:
    branches: [ "local-server" ]

jobs:

  build:
    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: sudo docker compose up --build
